version: '3.7'
services:
  appserver:
    image: 'go_songs'
    ports:
    - target: 8000
      published: 8000
      protocol: tcp
      mode: host
    depends_on:
    - 'db'
  db:
    image: 'mongo'
    ports:
    - target: 27017
      published: 27017
      protocol: tcp
      mode: host